/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.ResultSet;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ramadhan
 */
public class AktifitasTransaksi extends javax.swing.JFrame {

    main_sc sc = new main_sc();
    private ResultSet hasil;
    NumberFormat formatRp = NumberFormat.getCurrencyInstance(new Locale("in", "ID"));
    DefaultTableModel tabmode;

    /**
     * Creates new form AktifitasTransaksi
     */
    public AktifitasTransaksi() {
        initComponents();
        tabAktif.setAutoResizeMode(tabAktif.AUTO_RESIZE_OFF);
        tabAktif.getColumnModel().getColumn(0).setPreferredWidth(80);
        tabAktif.getColumnModel().getColumn(1).setPreferredWidth(80);
        tabAktif.getColumnModel().getColumn(2).setPreferredWidth(188);
        tabAktif.getColumnModel().getColumn(3).setPreferredWidth(95);
        tabAktif.getColumnModel().getColumn(4).setPreferredWidth(85);
        tabAktif.getColumnModel().getColumn(5).setPreferredWidth(95);
        tabAktif.getColumnModel().getColumn(6).setPreferredWidth(50);
        tabAktif.getColumnModel().getColumn(7).setPreferredWidth(120);
        tabAktif.getColumnModel().getColumn(8).setPreferredWidth(300);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabAktif = new javax.swing.JTable();
        lab_totPendapatan = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/#3DE2FF.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1170, 670));
        setPreferredSize(new java.awt.Dimension(1170, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Pilih Tanggal Aktifitas Transaksi:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        jDateChooser1.setDateFormatString("dd-MM-yyyy");
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 120, -1));

        tabAktif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Waktu Pesan", "Kode Barang", "Nama Barang", "Jumlah Barang ", "Harga Satuan", "Harga Total", "Diskon", "Total Setelah Diskon", "Keterangan"
            }
        ));
        tabAktif.setName(""); // NOI18N
        jScrollPane1.setViewportView(tabAktif);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 1100, 350));

        lab_totPendapatan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(lab_totPendapatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 590, 220, 30));

        btn_ok.setBackground(new java.awt.Color(0, 102, 255));
        btn_ok.setForeground(new java.awt.Color(255, 255, 255));
        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 50, -1));

        btn_back.setBackground(new java.awt.Color(255, 204, 0));
        btn_back.setText("Kembali");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Riwayat Aktifitas Transaksi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOGO FINAL.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 260, 80));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/#3DE2FF.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 1130, 110));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/#3DE2FF.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        SimpleDateFormat format = new SimpleDateFormat("ddMMyyyy");
        String tanggal = String.valueOf(format.format(jDateChooser1.getDate()));
        tabmode = (DefaultTableModel) tabAktif.getModel();
        try {
            hasil = sc.tampilAktifitasTransaksi(tanggal);
            while (hasil.next()) {
                String waktu = hasil.getString("waktu_pembelian");
                String kodeBarang = hasil.getString("kode_barang");
                String namaBarang = hasil.getString("nama_barang");
                String jumlahBarang = hasil.getString("jumlah_barang");
                int hargaSatuan = hasil.getInt("harga_satuan");
                int hargaTotal = hasil.getInt("harga_total");
                String diskon = hasil.getString("diskon");
                int totalSetelahDiskon = hasil.getInt("totalSetelahDiskon");
                String keterangan = hasil.getString("keterangan");
                String[] data = {waktu, kodeBarang, namaBarang, jumlahBarang, formatRp.format(hargaSatuan), formatRp.format(hargaTotal), diskon, formatRp.format(totalSetelahDiskon), keterangan};
                tabmode.addRow(data);
            }
            tabAktif.setModel(tabmode);
            double hargaAll = 0;
            for (int i = 0; i < tabAktif.getRowCount(); i++) {
                hargaAll += Double.parseDouble((String) tabAktif.getValueAt(i, 7).toString()
                        .replace("Rp", "").replace(".", "").replace(",00", ""));
            }
            lab_totPendapatan.setText("Total Pendapatan: " + formatRp.format(hargaAll));
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AktifitasTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AktifitasTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AktifitasTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AktifitasTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AktifitasTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_ok;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab_totPendapatan;
    private javax.swing.JTable tabAktif;
    // End of variables declaration//GEN-END:variables
}
