/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Collections;
import java.util.Locale;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author Ramadhan
 */
public class DataBarang extends javax.swing.JFrame {

    main_sc sc = new main_sc();
    private ResultSet hasil;
    private DefaultTableModel tabmode;
    NumberFormat formatRp = NumberFormat.getCurrencyInstance(new Locale("in", "ID"));

    /**
     * Creates new form DataBarang
     */
    public DataBarang() {
        initComponents();
        display();
    }

    public void display() {
        try {
            hasil = sc.tampilDataBarang();
            tabmode = (DefaultTableModel) tabDataBarang.getModel();
            while (hasil.next()) {
                String kodeBarang = hasil.getString("kode_barang");
                String namaBarang = hasil.getString("nama_barang");
                sc.setStokBarang(hasil.getString("stok_barang"));
                double hargaSatuan = hasil.getDouble("harga_satuan");
                String[] data = {kodeBarang, namaBarang, sc.getStokBarang(), formatRp.format(hargaSatuan)};
                tabmode.addRow(data);
            }
            tabDataBarang.setAutoCreateRowSorter(true);
            TableRowSorter sorter = (TableRowSorter) tabDataBarang.getRowSorter();
            sorter.setSortKeys(Collections.singletonList(new RowSorter.SortKey(0, SortOrder.ASCENDING)));
            tabDataBarang.setModel(tabmode);
            tabDataBarang.setRowHeight(25);
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    public void reset() {
        tf_kodeBarang.setText("");
        tf_namaBarang.setText("");
        tf_stok.setText("");
        tf_hargaSatuan.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabDataBarang = new javax.swing.JTable();
        tf_namaBarang = new javax.swing.JTextField();
        tf_hargaSatuan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_kodeBarang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_stok = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_updateBarang = new javax.swing.JButton();
        btn_tambahBarang = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_hapusBarang = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tf_pencarian = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(666, 575));
        setPreferredSize(new java.awt.Dimension(666, 575));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Data Barang");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        tabDataBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Stok", "Harga Satuan"
            }
        ));
        tabDataBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabDataBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabDataBarang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 620, 260));
        getContentPane().add(tf_namaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 220, -1));
        getContentPane().add(tf_hargaSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 160, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Stok");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, -1, -1));
        getContentPane().add(tf_kodeBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 120, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Kode Barang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));
        getContentPane().add(tf_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 50, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Nama Barang");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Harga Satuan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, -1, -1));

        btn_updateBarang.setBackground(new java.awt.Color(102, 153, 255));
        btn_updateBarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_updateBarang.setText("Update Barang");
        btn_updateBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateBarangActionPerformed(evt);
            }
        });
        getContentPane().add(btn_updateBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, -1, -1));

        btn_tambahBarang.setBackground(new java.awt.Color(102, 153, 255));
        btn_tambahBarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_tambahBarang.setText("Tambah Barang");
        btn_tambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahBarangActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambahBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        btn_reset.setBackground(new java.awt.Color(204, 0, 0));
        btn_reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, -1, -1));

        btn_hapusBarang.setBackground(new java.awt.Color(204, 0, 0));
        btn_hapusBarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_hapusBarang.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapusBarang.setText("Hapus Barang");
        btn_hapusBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusBarangActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapusBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));

        jLabel3.setText("Pencarian:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, 20));

        tf_pencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_pencarianKeyReleased(evt);
            }
        });
        getContentPane().add(tf_pencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 170, -1));

        btn_back.setBackground(new java.awt.Color(255, 204, 51));
        btn_back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_back.setText("Kembali");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOGO FINAL.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 260, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/#3DE2FF.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabDataBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabDataBarangMouseClicked
        try {
            int row = tabDataBarang.rowAtPoint(evt.getPoint());
            String kodeBarang = tabDataBarang.getValueAt(row, 0).toString();
            String namaBarang = tabDataBarang.getValueAt(row, 1).toString();
            String stok = tabDataBarang.getValueAt(row, 2).toString();
            String hargaSatuan = tabDataBarang.getValueAt(row, 3).toString();
            tf_kodeBarang.setText(kodeBarang);
            tf_namaBarang.setText(namaBarang);
            tf_stok.setText(stok);
            tf_hargaSatuan.setText(hargaSatuan);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tabDataBarangMouseClicked

    private void btn_updateBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateBarangActionPerformed
        if (tf_kodeBarang.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Kode barang belum diisi !");
            tf_kodeBarang.requestFocus();
        } else if (tf_namaBarang.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Nama barang belum diisi !");
            tf_namaBarang.requestFocus();
        } else if (tf_stok.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Stok belum diisi !");
            tf_stok.requestFocus();
        } else if (tf_hargaSatuan.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Harga Satuan belum diisi !");
            tf_hargaSatuan.requestFocus();
        } else {
            try {
                int pilihan = JOptionPane.showConfirmDialog(null, "Apakah Mau Update barang?", "Update Barang", JOptionPane.YES_NO_OPTION);
                if (pilihan == JOptionPane.YES_OPTION) {
                    String hargaSatu = tf_hargaSatuan.getText().replace("Rp", "").replace(".", "").replace(",00", "");
                    sc.updateBarang(tf_kodeBarang.getText(), tf_namaBarang.getText(), tf_stok.getText(), hargaSatu);
                    int rowCount = tabmode.getRowCount();
                    for (int i = rowCount - 1; i >= 0; i--) {
                        tabmode.removeRow(i);
                    }
                    sc.catatAktifitas(tf_kodeBarang.getText(), tf_namaBarang.getText(), tf_stok.getText(), hargaSatu, 0, "0", 0, "Stok Menambah atau Harga Berubah");
                    display();
                    reset();
                } else {

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data gagal tersimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_updateBarangActionPerformed

    private void btn_tambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahBarangActionPerformed
        int pilihan = JOptionPane.showConfirmDialog(null, "Apakah Mau Menambah barang?", "Tambah Barang", JOptionPane.YES_NO_OPTION);
        if (pilihan == JOptionPane.YES_OPTION) {
            String hargaSatu = tf_hargaSatuan.getText().replace("Rp", "").replace(".", "").replace(",00", "");
            sc.barangBaru(tf_kodeBarang.getText(), tf_namaBarang.getText(), tf_stok.getText(), hargaSatu);
            int rowCount = tabmode.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) {
                tabmode.removeRow(i);
            }
            sc.catatAktifitas(tf_kodeBarang.getText(), tf_namaBarang.getText(), tf_stok.getText(), hargaSatu, 0, "0", 0, "Barang Baru Datang");
            reset();
            display();
        } else {

        }
    }//GEN-LAST:event_btn_tambahBarangActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        reset();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_hapusBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusBarangActionPerformed
        int pilihan = JOptionPane.showConfirmDialog(null, "Apakah Mau Menghapus barang?", "Hapus Barang", JOptionPane.YES_NO_OPTION);
        if (pilihan == JOptionPane.YES_OPTION) {
            sc.hapusBarang(tf_kodeBarang.getText());
            int rowCount = tabmode.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) {
                tabmode.removeRow(i);
            }
            String hargaSatuan = tf_hargaSatuan.getText().replace("Rp", "").replace(".", "").replace(",00", "");
            sc.catatAktifitas(tf_kodeBarang.getText(), tf_namaBarang.getText(), tf_stok.getText(), hargaSatuan, 0, "0", 0, "Barang Dihapus");
            reset();
            display();
        }
    }//GEN-LAST:event_btn_hapusBarangActionPerformed

    private void tf_pencarianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pencarianKeyReleased
        String cari = tf_pencarian.getText();
        TableRowSorter tr = new TableRowSorter(tabmode);
        tabDataBarang.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(cari, 0, 1));
    }//GEN-LAST:event_tf_pencarianKeyReleased

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_hapusBarang;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_tambahBarang;
    private javax.swing.JButton btn_updateBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabDataBarang;
    private javax.swing.JTextField tf_hargaSatuan;
    private javax.swing.JTextField tf_kodeBarang;
    private javax.swing.JTextField tf_namaBarang;
    private javax.swing.JTextField tf_pencarian;
    private javax.swing.JTextField tf_stok;
    // End of variables declaration//GEN-END:variables
}
