
import java.awt.event.KeyEvent;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Ramadhan
 */
public class pembayaran extends javax.swing.JFrame {

    NumberFormat formatRp = NumberFormat.getCurrencyInstance(new Locale("in", "ID"));

    /**
     * Creates new form payment
     */
    public pembayaran() {
        initComponents();
        lab_hargaTotal.setText(setterGetter.getHargaTotal());
        lab_total.setText(setterGetter.getHargaTotal());
        tf_diskon.requestFocus();
        setterGetter.setTotalKeseluruhan(lab_total.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlabel1 = new javax.swing.JLabel();
        lab_hargaTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_diskon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lab_diskon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lab_total = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_nom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lab_kembalian = new javax.swing.JLabel();
        btn_kembali = new javax.swing.JButton();
        btn_cetakStruk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pembayaran");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, -1));

        jlabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel1.setText("Harga Total Pesanan:");
        getContentPane().add(jlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 25));

        lab_hargaTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(lab_hargaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 170, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Diskon");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 25));

        tf_diskon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_diskonKeyPressed(evt);
            }
        });
        getContentPane().add(tf_diskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 25, 25));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("%        :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 25));

        lab_diskon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(lab_diskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 170, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Total                     :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, 25));

        lab_total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(lab_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 170, 25));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Pembayaran            :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 25));

        tf_nom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_nomKeyPressed(evt);
            }
        });
        getContentPane().add(tf_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 170, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Kembalian              :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 140, 25));

        lab_kembalian.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(lab_kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 170, 25));

        btn_kembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, 24));

        btn_cetakStruk.setBackground(new java.awt.Color(0, 51, 255));
        btn_cetakStruk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cetakStruk.setForeground(new java.awt.Color(255, 255, 255));
        btn_cetakStruk.setText("Cetak Struk");
        btn_cetakStruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakStrukActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cetakStruk, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cetakStrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakStrukActionPerformed
        if (tf_diskon.getText().trim().equals("")) {
            setterGetter.setDiskon("0");
            setterGetter.setHasilKurangDiskon("0");
        } else {
            setterGetter.setDiskon(tf_diskon.getText());
            setterGetter.setHasilKurangDiskon(lab_diskon.getText().replace("Rp", "").replace(",00", ""));
        }
        CetakStruk cs = new CetakStruk();
        cs.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_cetakStrukActionPerformed

    private void tf_nomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nomKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            double nom = Double.parseDouble(tf_nom.getText().replace("Rp", "").replace(".", "").replace(",00", ""));
            setterGetter.setNominal(tf_nom.getText());
            double tot = Double.parseDouble(lab_total.getText().replace("Rp", "").replace(".", "").replace(",00", ""));
            if (nom < tot) {
                JOptionPane.showMessageDialog(null, "Maaf, Nominal Uang yang Diinput kurang");
            } else {
                double kembali = nom - tot;
                lab_kembalian.setText(formatRp.format(kembali));
                setterGetter.setKembalian(lab_kembalian.getText().replace("Rp", "").replace(",00", ""));
            }
        }
    }//GEN-LAST:event_tf_nomKeyPressed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        main_sc sc = new main_sc();
        sc.returBarang("", "");
        dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void tf_diskonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_diskonKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            double diskon = Double.parseDouble(tf_diskon.getText()) / 100
                    * Double.parseDouble(lab_hargaTotal.getText().replace("Rp", "").replace(".", "").replace(",00", ""));
            lab_diskon.setText(formatRp.format(diskon));

            double total = Double.parseDouble(lab_hargaTotal.getText().replace("Rp", "").replace(".", "").replace(",00", ""))
                    - diskon;
            lab_total.setText(formatRp.format(total));
            setterGetter.setTotalKeseluruhan(formatRp.format(total).replace("Rp", "").replace(",00", ""));
        }
    }//GEN-LAST:event_tf_diskonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cetakStruk;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel lab_diskon;
    private javax.swing.JLabel lab_hargaTotal;
    private javax.swing.JLabel lab_kembalian;
    private javax.swing.JLabel lab_total;
    private javax.swing.JTextField tf_diskon;
    private javax.swing.JTextField tf_nom;
    // End of variables declaration//GEN-END:variables
}
